"""create mixes posts likes comments shares tables

Revision ID: a9e94f938056
Revises: fa05db26d519
Create Date: 2026-07-27 10:29:18.513739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e94f938056'
down_revision: Union[str, Sequence[str], None] = 'fa05db26d519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mixes_creator_id'), 'mixes', ['creator_id'], unique=False)
    op.create_index(op.f('ix_mixes_id'), 'mixes', ['id'], unique=False)
    op.create_table('mix_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('audio_url', sa.String(length=1000), nullable=False),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('start_second', sa.Integer(), nullable=False),
    sa.Column('end_second', sa.Integer(), nullable=False),
    sa.Column('transition_to_next', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_track_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mix_id', 'position', name='uq_mix_segments_mix_position')
    )
    op.create_index(op.f('ix_mix_segments_id'), 'mix_segments', ['id'], unique=False)
    op.create_index(op.f('ix_mix_segments_mix_id'), 'mix_segments', ['mix_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mix_id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_author_id'), 'post_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_comments_id'), 'post_comments', ['id'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('post_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_shares_post_user')
    )
    op.create_index(op.f('ix_post_shares_id'), 'post_shares', ['id'], unique=False)
    op.create_index(op.f('ix_post_shares_post_id'), 'post_shares', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_shares_user_id'), 'post_shares', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_shares_user_id'), table_name='post_shares')
    op.drop_index(op.f('ix_post_shares_post_id'), table_name='post_shares')
    op.drop_index(op.f('ix_post_shares_id'), table_name='post_shares')
    op.drop_table('post_shares')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_id'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_author_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_mix_segments_mix_id'), table_name='mix_segments')
    op.drop_index(op.f('ix_mix_segments_id'), table_name='mix_segments')
    op.drop_table('mix_segments')
    op.drop_index(op.f('ix_mixes_id'), table_name='mixes')
    op.drop_index(op.f('ix_mixes_creator_id'), table_name='mixes')
    op.drop_table('mixes')
    # ### end Alembic commands ###
