"""create profiles and play events tables

Revision ID: e2bc2720152c
Revises: a9e94f938056
Create Date: 2026-07-27 11:59:17.542523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2bc2720152c'
down_revision: Union[str, Sequence[str], None] = 'a9e94f938056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('bio', sa.String(length=280), nullable=True),
    sa.Column('favorite_genres', sa.JSON(), nullable=True),
    sa.Column('theme_preference', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("theme_preference IN ('dark', 'light', 'system')", name='ck_profiles_theme_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('play_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('seconds_listened', sa.Integer(), nullable=False),
    sa.Column('client_event_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['mix_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_play_events_created_at'), 'play_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_play_events_id'), 'play_events', ['id'], unique=False)
    op.create_index(op.f('ix_play_events_mix_id'), 'play_events', ['mix_id'], unique=False)
    op.create_index(op.f('ix_play_events_post_id'), 'play_events', ['post_id'], unique=False)
    op.create_index(op.f('ix_play_events_segment_id'), 'play_events', ['segment_id'], unique=False)
    op.create_index(op.f('ix_play_events_user_id'), 'play_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_play_events_user_id'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_segment_id'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_post_id'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_mix_id'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_id'), table_name='play_events')
    op.drop_index(op.f('ix_play_events_created_at'), table_name='play_events')
    op.drop_table('play_events')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
