"""add social mixes

Revision ID: f3dc072dcac2
Revises: 92efbb2c2a49
Create Date: 2026-07-12 17:28:12.865973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dc072dcac2'
down_revision: Union[str, Sequence[str], None] = '92efbb2c2a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mixes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('prompt', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mixes_owner_id'), 'mixes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_mixes_status'), 'mixes', ['status'], unique=False)
    op.create_table('mix_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mix_id', name='uq_user_mix_like')
    )
    op.create_index(op.f('ix_mix_likes_mix_id'), 'mix_likes', ['mix_id'], unique=False)
    op.create_index(op.f('ix_mix_likes_user_id'), 'mix_likes', ['user_id'], unique=False)
    op.create_table('mix_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('start_second', sa.Integer(), nullable=False),
    sa.Column('end_second', sa.Integer(), nullable=False),
    sa.Column('transition_to_next', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_track_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mix_id', 'position', name='uq_mix_segment_position')
    )
    op.create_index(op.f('ix_mix_segments_mix_id'), 'mix_segments', ['mix_id'], unique=False)
    op.create_table('saved_mixes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mix_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mix_id'], ['mixes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mix_id', name='uq_user_saved_mix')
    )
    op.create_index(op.f('ix_saved_mixes_mix_id'), 'saved_mixes', ['mix_id'], unique=False)
    op.create_index(op.f('ix_saved_mixes_user_id'), 'saved_mixes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_mixes_user_id'), table_name='saved_mixes')
    op.drop_index(op.f('ix_saved_mixes_mix_id'), table_name='saved_mixes')
    op.drop_table('saved_mixes')
    op.drop_index(op.f('ix_mix_segments_mix_id'), table_name='mix_segments')
    op.drop_table('mix_segments')
    op.drop_index(op.f('ix_mix_likes_user_id'), table_name='mix_likes')
    op.drop_index(op.f('ix_mix_likes_mix_id'), table_name='mix_likes')
    op.drop_table('mix_likes')
    op.drop_index(op.f('ix_mixes_status'), table_name='mixes')
    op.drop_index(op.f('ix_mixes_owner_id'), table_name='mixes')
    op.drop_table('mixes')
    # ### end Alembic commands ###
