/**
 * Purpose:
 * Shared frontend data contracts for the Smart AI DJ app.
 *
 * How this connects to the project:
 * The frontend currently works with mock session data. Later, the backend will
 * return real JSON from endpoints such as POST /sessions/start and
 * POST /sessions/{id}/feedback. These JSDoc typedefs document the shape of that
 * data so components, stores, and services all agree on the same contract.
 *
 * Engineering decision:
 * We are using JavaScript with JSDoc instead of full TypeScript. This keeps the
 * project simple for the team while still giving VS Code autocomplete and useful
 * type checking. If the backend changes the JSON shape later, this file should be
 * updated first.
 */

/**
 * Main lifecycle states for the continuous AI DJ session.
 *
 * idle           = no session has started yet.
 * starting       = the first session/chunk is being prepared.
 * playing        = the AI DJ session is active.
 * buffering_next = future state for preparing the next continuation chunk.
 * stopped        = the user intentionally stopped the current session.
 * error          = a user-friendly failure state.
 *
 * @typedef {"idle" | "starting" | "playing" | "buffering_next" | "stopped" | "error"} AppStatus
 */

/**
 * Quick prompt suggestion shown as a chip under the prompt box.
 *
 * @typedef {Object} Preset
 * @property {string} label - Short chip label shown to the user.
 * @property {string} prompt - Full prompt inserted into the prompt composer.
 */

/**
 * User-facing metadata for the currently playing song moment.
 *
 * This is intentionally not a raw ML segment object. The normal user should see
 * familiar music-player information, not model scores, segment ids, or graph edges.
 *
 * @typedef {Object} NowPlaying
 * @property {string} title - Current song or track title shown in the player.
 * @property {string} artist - Artist name.
 * @property {string} album - Album, playlist, or catalog/source label.
 * @property {string} coverUrl - Cover image URL generated by Vite or returned by backend.
 * @property {string} vibeLabel - Human-friendly vibe label, e.g. "Late Night Piano Flow".
 * @property {string} role - Simplified musical role, e.g. "Warm intro".
 */

/**
 * Optional human explanation for demo/lecturer mode.
 *
 * This replaces the old always-visible timeline and score dashboard. The normal
 * player stays clean, while the team can still prove the AI DJ is making choices.
 *
 * @typedef {Object} AIReasoning
 * @property {string} selectedBecause - Why the current song moment matches the vibe.
 * @property {string} transitionPlan - Human explanation of the transition direction.
 * @property {string} nextDirection - What the AI DJ intends to do next.
 */

/**
 * A running AI DJ session.
 *
 * In the real backend, this object will likely be created by POST /sessions/start.
 * Later versions may include queue/chunk ids, audio URLs, and streaming state.
 *
 * @typedef {Object} DJSession
 * @property {string} id - Stable session id.
 * @property {string} prompt - User prompt used to start the session.
 * @property {NowPlaying} nowPlaying - Current visible player metadata.
 * @property {AIReasoning} reasoning - Optional explanation shown only when requested.
 */

/**
 * Single source of truth for the home page UI.
 *
 * The Svelte store owns this shape. Components receive slices of this state as
 * props and call store actions for changes.
 *
 * @typedef {Object} SessionState
 * @property {AppStatus} status - Current lifecycle status of the AI DJ session.
 * @property {string} prompt - User-written vibe prompt.
 * @property {string} currentStep - Current startup/buffering step shown to the user.
 * @property {number} progress - Startup/buffering progress percentage.
 * @property {DJSession | null} session - Current active or stopped session.
 * @property {boolean} isPlaying - Whether playback is currently active.
 * @property {boolean} showReasoning - Whether optional AI reasoning is open.
 * @property {string | null} selectedFeedback - Last clicked feedback option.
 * @property {string | null} error - Friendly error message shown to users.
 */

export {};
