# Use an official Python runtime as a parent image
FROM python:3.9-slim
# Set the working directory inside the container
WORKDIR /app
# Copy dependency list into container
COPY requirements.txt .
# Install Python dependencies without caching
RUN pip install -r requirements.txt
# Copy the application code into the container
COPY . .
# Expose Flasks default port
EXPOSE 5000
# Start the Flask development server
CMD ["python", "main.py", "--port", "5000"]
